apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace "org.hyperskill.photoeditor"
    compileSdk hs.android.compileSdkVersion

    defaultConfig {
        applicationId "org.hyperskill.photoeditor"
        minSdkVersion hs.android.minSdkVersion
        targetSdkVersion hs.android.targetSdkVersion
        versionCode 1
        versionName '1.0'
    }

    buildFeatures {
        viewBinding true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }

    sourceSets {
        test {
            java.srcDirs = ['test/java']
        }
    }
}

dependencies {
    def coreKtx = hs.android.lib.coreKtx
    implementation "androidx.core:core-ktx:$coreKtx"

    def appCompat = hs.android.lib.appCompat
    implementation "androidx.appcompat:appcompat:$appCompat"

    def constraintLayout = hs.android.lib.constraintLayout
    implementation "androidx.constraintlayout:constraintlayout:$constraintLayout"

    def material = hs.android.lib.material
    implementation "com.google.android.material:material:$material"
    
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.9"
}
